name: Build

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color --codes -q"
          annotate: warning
      - name: Create Retail Package
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Classic Package
        uses: BigWigsMods/packager@master
        with:
          args: "-g classic"
        env:
          CF_API_KEY: ${{ secrets.CF_API_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      - name: Create BC Package
        uses: BigWigsMods/packager@master
        with:
          args: "-g bc"
        env:
          CF_API_KEY: ${{ secrets.CF_API_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
